version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: todo_db
    ports:
      - "3306:3306"
    networks:
      - my_network

  python:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: python_container
    working_dir: /app
    volumes:
      - ./app:/app
    networks:
      - my_network
    ports:
      - "5000:5000"
    command: python main.py

networks:
  my_network:
